# This is a basic workflow to help you get started with Actions

- name: Wiki Sync
  uses: JoeIzzard/ghaction-wiki-sync@v1

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: joeizzard/action-wiki-sync@master
            with:
                username: LachlanDog
                access_token: ${{ secrets.GITHUB_TOKEN }}
                wiki_folder: wiki
                commit_username: 'LachlanDog'
                commit_email: 'LachlanDog@users.noreply.github.com'
                commit_message: 'action: wiki sync'
